# Add application configuration variables here, as shown below.

STRIPE_API_KEY: sk_test_xIZHuNvWU7FprwSeYziNKSEh
STRIPE_PUBLIC_KEY: pk_test_0vpenXfCEPd4WFCCWLkeuJhr
S3_ACCESS_KEY: AKIAJEJ4Y7CXETXMGLHA
S3_SECRET_ACCESS_KEY: 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
S3_BUCKET: homepros-development
DB_USERNAME: derrick
DB_PASSWORD: 